@BryShort.API.V1_HostAddress = http://localhost:5277

GET {{BryShort.API.V1_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{BryShort.API.V1_HostAddress}}/api/users
Content-Type: application/json

{
"UserName": "alfredo_rp",
"Password": "algo"
}


###
POST {{BryShort.API.V1_HostAddress}}/api/links
Content-Type: application/json

{
"ShortUrl": "plazi",
"UrlTo": "https://platzi.com",
"ExpiresAt": null
}